import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/common";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const NotoSans = Noto_Sans({
  variable: "--font-noto-sans",
});

const NotoSansMono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
});

export const metadata: Metadata = {
  title: "Seokjun.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${NotoSans.variable} ${NotoSansMono.variable} page antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
